# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='tags',
            field=models.ManyToManyField(to='market.Tag'),
        ),
    ]
