# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20161226_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
