# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20161227_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UInfo',
        ),
        migrations.AlterField(
            model_name='commodity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
