# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_uinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='uinfo',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uinfo',
            name='qq',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
