# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20161227_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='image',
            field=models.ImageField(upload_to='uploads/commodity'),
        ),
        migrations.AlterField(
            model_name='uinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/avatar'),
        ),
    ]
